import Head from "next/head";

export default function Layout({ children }) {
    return (
      <>
      <Head>
        <title>TogetherAll TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            {children}
        </main>
        <footer>
            <p>Copyright &copy; {'2021'}</p>
        </footer>
      </>
    )
  }